# Generated by Django 2.0.5 on 2018-05-10 15:36

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', utils.models.CurrencyField(decimal_places=2, max_digits=9)),
                ('from_account', models.ForeignKey(on_delete='cascade', related_name='from_payments', to='accounts.Account')),
                ('to_account', models.ForeignKey(on_delete='cascade', related_name='to_payments', to='accounts.Account')),
            ],
        ),
    ]
